### ISSUE TITLE
How to open terminal from Docker GUI

### ISSUE THREAD

**Issue by marianfoo** [SAP-samples/cloud-btp-cli-api-codejam#12]
When you open the terminal from the Docker GUI as a external terminal, you need to run `bash`:
<img width="407" alt="image" src="https://user-images.githubusercontent.com/13335743/191914825-aaf4713a-f974-46bc-8692-0d5891f4075f.png">
<img width="675" alt="image" src="https://user-images.githubusercontent.com/13335743/191914911-19279025-a00e-47bb-abfd-4479894abd4f.png">

Would good if this is in the documentation as well

**Comment by qmacro** [comment]
Thanks again @marianfoo , I'll add some notes. 

[The instructions are to start a container from the command line](https://github.com/SAP-samples/cloud-btp-cli-api-codejam/tree/main/container#create-a-container) but I'll let you off this time ;-)

**Comment by qmacro** [comment]
Not being a GUI-first user, I've never done this before, so I tried it and got the same result. So I did some research, and using the "CLI" feature from the Docker Desktop GUI places you in a `sh` environment. According to the Docker Desktop GUI documentation for this, the [Explore Containers](https://docs.docker.com/desktop/use-desktop/container) section says:

> You also have the option to open an integrated terminal, on a running container, directly within Docker Desktop. This allows you to quickly execute commands within your container so you can understand its current state or debug when something goes wrong.
> Using the integrated terminal is the same as running `docker exec -it <container-id> /bin/sh`

This makes sense, in that it allows you to connect to the container in the normal (`exec`) way.
