### ISSUE TITLE
Exercise 6 Request the token fails with no such host

### ISSUE THREAD

**Issue by jung-thomas** [SAP-samples/cloud-btp-cli-api-codejam#27]
https://github.com/SAP-samples/cloud-btp-cli-api-codejam/blob/main/exercises/06-core-services-api-creds/README.md

When requesting the token with `./generate-password-grant-type cis-central-sk.json`, it fails in the Business Application Studio. However it is successful from the Docker container.

BAS:
![image](https://user-images.githubusercontent.com/12159356/210428718-e5bb116f-a707-4499-8c49-8093241119cf.png)

Docker:
![image](https://user-images.githubusercontent.com/12159356/210428746-8df0262a-9009-4aa2-9aad-0ca6c07324b4.png)

Error Message in BAS:
``` Shell
Username (email address): thomas.jung@sap.com
Password for 'thomas.jung@sap.com': dial tcp: lookup null on 100.64.0.10:53: no such host
```

**Comment by qmacro** [comment]
The latest BAS now has `cf` version 8 installed by default. Astonishingly, the JSON output produced, **for the same request**, between `cf` version 7 and version 8, **has a different structure**:

Version 7 (`cf version 7.5.0+0ad1d63.2022-06-04`):

```json
{
  "endpoints": {
    "accounts_service_url": "https://accounts-service.cfapps.eu10.hana.ondemand.com",
    "cloud_automation_url": "https://cp-formations.cfapps.eu10.hana.ondemand.com"
  },
  "grant_type": "user_token",
  "sap.cloud.service": "com.sap.core.commercial.service.central",
  "uaa": {
    "apiurl": "https://api.authentication.eu10.hana.ondemand.com",
    "clientid": "sb-ut-9d5c5eb7-486e-4575-8acb-0bbc944c6311-clone!b169670|cis-central!b14",
    "url": "https://65137137trial-ga.authentication.eu10.hana.ondemand.com"
  }
}
```

Version 8 (`cf8 version 8.5.0+73aa161.2022-09-12`):

```json
{
  "credentials": {
    "endpoints": {
      "accounts_service_url": "https://accounts-service.cfapps.eu10.hana.ondemand.com",
      "cloud_automation_url": "https://cp-formations.cfapps.eu10.hana.ondemand.com"
    },
    "grant_type": "user_token",
    "sap.cloud.service": "com.sap.core.commercial.service.central",
    "uaa": {
      "apiurl": "https://api.authentication.eu10.hana.ondemand.com",
      "clientid": "sb-ut-9d5c5eb7-486e-4575-8acb-0bbc944c6311-clone!b169670|cis-central!b14",
      "url": "https://65137137trial-ga.authentication.eu10.hana.ondemand.com"
    }
  }
}
```

In other words, version 8 of `cf` wraps the output JSON (specifically the `endpoints` and `uaa` properties) inside a new outermost property `credentials`).

Last time I ran this CodeJam the version of `cf` in BAS was 7. But I wouldn't have expected JSON output to change so significantly between `cf` versions! 

I'll address this shortly. Thanks for catching!
